// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package inf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRq) Reset()         { *m = UserRq{} }
func (m *UserRq) String() string { return proto.CompactTextString(m) }
func (*UserRq) ProtoMessage()    {}
func (*UserRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *UserRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRq.Unmarshal(m, b)
}
func (m *UserRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRq.Marshal(b, m, deterministic)
}
func (m *UserRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRq.Merge(m, src)
}
func (m *UserRq) XXX_Size() int {
	return xxx_messageInfo_UserRq.Size(m)
}
func (m *UserRq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRq proto.InternalMessageInfo

func (m *UserRq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserRp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRp) Reset()         { *m = UserRp{} }
func (m *UserRp) String() string { return proto.CompactTextString(m) }
func (*UserRp) ProtoMessage()    {}
func (*UserRp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *UserRp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRp.Unmarshal(m, b)
}
func (m *UserRp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRp.Marshal(b, m, deterministic)
}
func (m *UserRp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRp.Merge(m, src)
}
func (m *UserRp) XXX_Size() int {
	return xxx_messageInfo_UserRp.Size(m)
}
func (m *UserRp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRp.DiscardUnknown(m)
}

var xxx_messageInfo_UserRp proto.InternalMessageInfo

func (m *UserRp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Req struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type Resp struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRq)(nil), "inf.UserRq")
	proto.RegisterType((*UserRp)(nil), "inf.UserRp")
	proto.RegisterType((*Req)(nil), "inf.Req")
	proto.RegisterType((*Resp)(nil), "inf.Resp")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xcf, 0x4d, 0xaa, 0xc2, 0x40,
	0x0c, 0xc0, 0x71, 0xfa, 0xf9, 0x5e, 0x23, 0x88, 0x64, 0x63, 0x29, 0x5d, 0xc8, 0x88, 0x20, 0x08,
	0x5d, 0xd4, 0x2b, 0x08, 0xee, 0x03, 0x3d, 0x40, 0xb5, 0xa9, 0xcc, 0xc2, 0x36, 0x9d, 0x99, 0xfb,
	0x23, 0x1d, 0x2b, 0x08, 0xee, 0xfe, 0xe1, 0x07, 0x21, 0x01, 0x78, 0x18, 0xb9, 0x57, 0x62, 0x46,
	0x37, 0x62, 0xa4, 0x87, 0x5e, 0xe5, 0x90, 0x36, 0x96, 0x0d, 0x4d, 0xb8, 0x86, 0x50, 0x77, 0x79,
	0xb0, 0x0b, 0x8e, 0x09, 0x85, 0xba, 0x53, 0xe5, 0x22, 0x82, 0x08, 0xf1, 0xd0, 0x3e, 0xd9, 0x5b,
	0x46, 0xbe, 0xd5, 0x16, 0x22, 0xe2, 0x09, 0x37, 0x10, 0x59, 0x67, 0x16, 0x99, 0x53, 0xe5, 0x10,
	0x13, 0x5b, 0xf9, 0x95, 0xfa, 0x04, 0xf1, 0xa5, 0x75, 0x2d, 0xee, 0xe1, 0xef, 0xca, 0x6e, 0xde,
	0x8d, 0xab, 0x4a, 0x0f, 0x7d, 0xf5, 0x3e, 0xa0, 0xf8, 0x1a, 0xa4, 0x3e, 0x40, 0xd2, 0x88, 0xb0,
	0xc1, 0xf2, 0x13, 0xff, 0x9e, 0x89, 0xa7, 0x22, 0x5b, 0xca, 0xca, 0x2d, 0xf5, 0xaf, 0x9c, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0x31, 0x04, 0xa9, 0xd8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	GetUser(ctx context.Context, in *UserRq, opts ...grpc.CallOption) (*UserRp, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) GetUser(ctx context.Context, in *UserRq, opts ...grpc.CallOption) (*UserRp, error) {
	out := new(UserRp)
	err := c.cc.Invoke(ctx, "/inf.Data/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	GetUser(context.Context, *UserRq) (*UserRp, error)
}

// UnimplementedDataServer can be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (*UnimplementedDataServer) GetUser(ctx context.Context, req *UserRq) (*UserRp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.Data/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetUser(ctx, req.(*UserRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inf.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Data_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

// UpperClient is the client API for Upper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpperClient interface {
	Upper(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type upperClient struct {
	cc *grpc.ClientConn
}

func NewUpperClient(cc *grpc.ClientConn) UpperClient {
	return &upperClient{cc}
}

func (c *upperClient) Upper(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/inf.Upper/Upper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpperServer is the server API for Upper service.
type UpperServer interface {
	Upper(context.Context, *Req) (*Resp, error)
}

// UnimplementedUpperServer can be embedded to have forward compatible implementations.
type UnimplementedUpperServer struct {
}

func (*UnimplementedUpperServer) Upper(ctx context.Context, req *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upper not implemented")
}

func RegisterUpperServer(s *grpc.Server, srv UpperServer) {
	s.RegisterService(&_Upper_serviceDesc, srv)
}

func _Upper_Upper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpperServer).Upper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.Upper/Upper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpperServer).Upper(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Upper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inf.Upper",
	HandlerType: (*UpperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upper",
			Handler:    _Upper_Upper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
